apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mailcronjob-autoscaler
  namespace: smartinbox
  labels:
    mylabel: mailcronjob
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mailcronjob-deployment
  targetCPUUtilizationPercentage: 50
