apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mailservice-autoscaler
  namespace: smartinbox
  labels:
    mylabel: mailservice
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mailservice-deployment
  targetCPUUtilizationPercentage: 50
