apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userservice-autoscaler
  namespace: smartinbox
  labels:
    mylabel: userservice
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice-deployment
  targetCPUUtilizationPercentage: 50
