apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-frontend-autoscaler
  namespace: smartinbox
  labels:
    mylabel: user-frontend
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-frontend-deployment
  targetCPUUtilizationPercentage: 50
