apiVersion: v1
kind: Service
metadata:
  name: mailservice-service
  namespace: smartinbox
spec:
  type: NodePort
  selector:
    mylabel: mailservice
  ports:
    - protocol: TCP
      nodePort: 30003
      port: 8103
      targetPort: 8103