apiVersion: v1
kind: Service
metadata:
  name: otter-service
spec:
  selector:
    app: otter
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
      nodePort: 30007
  type: NodePort 