apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  namespace: smartinbox
spec:
  type: NodePort
  selector:
    mylabel: userservice
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 8100
      targetPort: 8100