apiVersion: v1
kind: Service
metadata:
  name: user-frontend-service
spec:
  type: NodePort
  selector:
    mylabel: user-frontend
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 80